### ISSUE TITLE
关于下载的时候校验的问题

### ISSUE THREAD

**Issue by taopoppy** [asoul-go/asouldocs#59]
下载的时候出现了这个问题，请问怎么解决，GO1.13版本

verifying github.com/russross/blackfriday@v1.5.2+incompatible/go.mod: github.com
/russross/blackfriday@v1.5.2+incompatible/go.mod: reading https://goproxy.cn/sum
db/sum.golang.org/lookup/github.com/russross/blackfriday@v1.5.2+incompatible: 40
4 Not Found

**Comment by unknwon** [comment]
我也没不知道。。直接下编译好的吧：https://github.com/peachdocs/peach/releases
